config/routes.rb
Rails.application.routes.draw do
  get 'user/show'

  get 'collection/show'

  post 'photo/uploader'

  resources :items

  resources :items do
    resources :photos, :only => [:create, :destroy]
  end

  get 'welcome/index'
  root 'welcome#index'

  get 'sobre', to: 'welcome#about'
  get 'contato', to: 'welcome#contact'
  get 'como-funciona', to: 'welcome#howtodo'
  get 'onde-comprar', to: 'welcome#wherebuy'
  post 'contato', to: 'welcome#email_sender'
  post 'promocao', to: 'welcome#promocao'
  post 'trade', to: 'welcome#trade_sender'
  get 'item-trade', to: 'items#trade'
  get 'promo', to: 'welcome#promo'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_scope :user do
  #  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:email_sender, :trade_sender]
  def index
    @article = Article.all
    @about = About.first
  end

  def about
    @about = About.first
  end

  def contact

  end

  def howtodo
  end

  def wherebuy
  end

  def promo
  end

  def promocao
    email = PromocaoMailer.send_proposal(name: params[:name], email: params[:email], whatssapp: params[:whats], message: params[:message]).deliver
     redirect_to "/promo", :alert => "Mensagem enviada com sucesso"
  end

  def email_sender
    email = ContactMailer.send_proposal(name: params[:name], email: params[:email], message: params[:message]).deliver
     redirect_to "/contato", :alert => "Mensagem enviada com sucesso"
  end

  def trade_sender
      email = TradeMailer.trade(name: params[:name], email: params[:email], message: params[:message], id: params[:item_id]).deliver
      redirect_to "/item-trade", :alert => "Mensagem enviada com sucesso"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<%= render "share/slide" %>

<section id="main-content">

     <div class="row">
       <div class="small-16 columns">
         <h1><%= @about.title %></h1>
         <div class="big-sep"></div>
       </div>
     </div>

     <div class="row">
       <div class="small-16 columns">
         <p>
           <%=raw @about.description %>
         </p>
       </div>
     </div>


</section>

app/views/welcome/contact.html.erb
<%= render "share/slide" %>

<section id="main-content">

  <div class="row">
    <div class="small-16 columns">
      <h1>Contato</h1>
      <div class="big-sep"></div>
    </div>
  </div>

  <div class="row">
    <div class="small-16 large-8 columns">
      <form id="" action="/contato" method="post">
        <label>
          <input type="text" placeholder="Nome" name="name" value="<%= current_user.name if current_user.present? %>">
        </label>

        <label>
          <input type="text" placeholder="Email" name="email">
        </label>

        <label>
          <textarea name="message" rows="8" cols="40" placeholder="O que me conta?"></textarea>
        </label>

        <button type="submit" class="lime-button" name="submit">Enviar</button>
      </form>
      <div id="note"></div>
    </div>
    <div class="small-16 large-7 columns addresses">
      <div class="row small-up-1 medium-up-2">
        <!--address-->
        <!--//address-->
      </div>
    </div>
  </div>

</section>

app/views/welcome/howtodo.html.erb
<%#= render "share/slide" %>

<section id="main-content">

     <div class="row">
       <div class="small-16 columns">
         <h1>Como Funciona</h1>
         <div class="big-sep"></div>
       </div>
     </div>

     <div class="row">
       <div class="small-16 columns">
         <p>
           <div class="video-container"><iframe width="100%" height="300" src="https://www.youtube.com/embed/xFvLCAmaCR0?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>
         </p>
       </div>
     </div>

     <div class="row">
       <div class="small-16 columns">
         <%=link_to "Cadastre seu IOIO <span>Seja o maior de todos</span>".html_safe, new_item_path, class:"button cta-button" %>
         <div class="big-sep"></div>
       </div>
     </div>


</section>

app/views/welcome/index.html.erb
<section id="home-slider">
  <!--slide -->
  <% Banner.background.each do |banner| %>
  <!--div style="background: url('<%#= banner.image.banner.url %>')"-->
  <div>
    <div class="row">
      <div class="small-16 columns">
        <div class="cta-text">
          <!--p> <span><%#= banner.description %></span></p-->
		<div class="small-16 large-16 columns"><%=link_to image_tag("https://ioiocapcom.com/ioiocapcom/img/0001.jpg") %></div>
	        <%=link_to "Promoção <br> <b>Eu tenho você nao tem!!<b>".html_safe, "/promo", class:"button promo cta-button" %> 
          <%=link_to "#{banner.button} <span>Seja o maior de todos</span>".html_safe, new_item_path, class:"button cta-button" %>

          <div class="small-16 large-16 columns">
            <div class="small-16 large-5 columns medalhome"><%=link_to image_tag("https://ioiocapcom.com/ioiocapcom/img/01.jpg"), collection_show_path(id: 6) %></div>
            <div class="small-16 large-5 columns medalhome"><%=link_to image_tag("https://ioiocapcom.com/ioiocapcom/img/02.jpg"), collection_show_path(id: 4) %></div>
            <div class="small-16 large-5 columns medalhome"><%=link_to image_tag("https://ioiocapcom.com/ioiocapcom/img/03.jpg"), collection_show_path(id: 9) %></div>
            <div class="small-16 large-5 columns medalhome"><%=link_to image_tag("https://ioiocapcom.com/ioiocapcom/img/04.jpg"), collection_show_path(id: 7) %></div>
            <div class="small-16 large-5 columns medalhome"><%=link_to image_tag("https://ioiocapcom.com/ioiocapcom/img/05.jpg"), collection_show_path(id: 8) %></div>
            <div class="small-16 large-5 columns medalhome"><%=link_to image_tag("https://ioiocapcom.com/ioiocapcom/img/06.jpg"), collection_show_path(id: 5) %></div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <!--//slide -->

</section>

<div class="content-top"></div>

<section id="main-content">
  <div class="row">
    <div class="small-16 columns">
      <article class="about-us-summary">
        <h2><%= @about.title %></h2>
        <p>
          <%= @about.description[0..200] %>...<%= link_to "Leia mais", "/sobre", class:"read-more" %>
        </p>
      </article>
    </div>
  </div>
  <div class="row">
    <div class="small-16 columns">
      <div class="big-sep"></div>
    </div>
  </div>
  <div class="row">

    <div id="featured-games" class="small-16 large-9 columns">
      <h2 class="title">Destaques</h2>

      <% @article.each do |a| %>
        <article>
          <div class="image-container">
            <% unless a.link.present? %>
              <%= image_tag a.image.medium, alt:"", class:"thumbnail"%>
            <% else %>
              <div class="video-container">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= a.link %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              </div>
            <% end %>
          </div>
          <h5> <a href="#"><%= a.title %></a></h5>
          <p><%= a.description %></p>
        </article>
      <% end %>

    </div>


    <aside class="small-16 large-6 columns">
      <!--notebook-->
      <div class="notebook">

        <header><h2 class="title">Top Colecionadores</h2></header>
        <div class="blog-entries notebook-pattern">
          <% if top_collections.blank? %>
            <h3>Seja o Primeiro</h3>
          <% end %>
          <% top_collections.each do |tc| %>
          <div class="entry row large-collapse">
            <div class="date small-4 large-3 columns">
              <p>Qtde:</p><span><%= tc.items.size %></span>
            </div>
            <div class="article-preview small-12 large-13 columns">
              <h6><a href="#"><%= tc.name %></a></h6>
              <p>Brasil - SP - São Paulo</p>
              <%= link_to "Veja mais", user_show_path(id: tc.id), class:"more" %>
              <a href="#" class="link"> &rsaquo;</a>
            </div>
          </div><!--//entry-->
          <% end %>


        </div>
      </div>
      <!--//notebook-->


    </aside>

  </div>
</section>

app/views/welcome/promo.html.erb
<section id="main-content">

  <div class="row">
    <div class="small-16 columns">
      <p>
        <div class="video-container"><iframe width="100%" height="400" src="https://www.youtube.com/embed/vqg3ggAtaG8?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="small-16 columns">
      <h1>Promoção</h1>
      <div class="big-sep"></div>
    </div>
  </div>

  <div class="row">

    <div class="small-16 large-8 columns">
      <p>
        Promoção eu tenho vc não tem! <br><br>

Para ganhar um Ioiô Capcom modelo Flowpack e muito fácil.<br>
Basta postar um vídeo nas redes sociais com pelo menos um Ioiô Capcom na mão e dizendo a frase ( Eu tenho vc não tem ) no mínimo 4 vezes e pronto vc já está participando da promoção. Se esse video chegar em pelo menos 100 visualizações e estiver seguindo todos os critérios da promoção, vc acaba de ganhar um Ioiô Capcom.
<br><br>
Critério da promoção:<br>
Seu vídeo precisa ter no maximo 45 segundos de duração ou mínimo de 20 segundos, e contendo na descrição as #eutenhovcnaotem #ioiocapcom #capcom.
<br><br>
O video deve ser gravado em HD não pode estar com a imagem tremendo nem escura e áudio baixo se estiver assim seu vídeo não será aceito.Esse é o mínimo de qualidade exigido.
<br><br>
Caso seu vídeo fique bem produzido e criativo vamos divulgar em nossas redes sociais, e vc vai ganhar mais um ioiô, modelo luxo capcom.
<br><br>
Promoção válida por 30 dias podendo se estender por mais 90 dias.<br>
Início da promoção 05/02/2018
Ou quando durar o estoque de 10.000 unidades de Ioiôs Flowpack
<br><br>
Caso vc ganhe um ioiô Capcom o prazo de envio do ioiô e no máximo 5 dias úteis após pagamento do frete.
Valor único de R$ 9.90 para todo Brasil.
<br><br>
Após o envio do vídeo ( link ) demora em média 07 dias úteis para validação, chegando uma msg em seu email.
<br><br>
Junto com esse email chegará um link de pagamento do frete no valor de R$ 9.90 após a confirmação do pagamento e a escolha do Ioiô preferido, estaremos enviando em um prazo máximo de 5 dias úteis seu Ioiô Capcom.
<br><br>
      </p>
    </div>

    <div class="small-16 large-8 columns">
      <form id="" action="/promocao" method="post">
        <label>
          <input type="text" placeholder="Nome" name="name" value="<%= current_user.name if current_user.present? %>">
        </label>

        <label>
          <input type="text" placeholder="Email" name="email">
        </label>

        <label>
          <input name="whats" type="text" placeholder="whatsapp para contato com DDD">
        </label>

        <label>
          <input name="message" type="text" placeholder="Link do video no youtube">
        </label>

        <button type="submit" class="lime-button" name="submit">Enviar</button>
      </form>
      <div id="note"></div>
    </div>
    <div class="small-16 large-7 columns addresses">
      <div class="row small-up-1 medium-up-2">
        <!--address-->
        <!--//address-->
      </div>
    </div>
  </div>

</section>

app/views/welcome/wherebuy.html.erb
<%= render "share/slide" %>

<section id="main-content">

     <div class="row">
       <div class="small-16 columns">
         <h1>Onde Comprar</h1>
         <div class="big-sep"></div>
       </div>
     </div>

     <div class="row">
       <div class="small-16 columns" style="background-color: white;padding-bottom: 20px;">
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/americanas.png"), "https://www.americanas.com.br/busca/ioio-capcom", target:"_blank" %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/magazine.png"), "https://busca.magazineluiza.com.br/busca?q=ioio+capcom", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/mundopop.png"), "http://portalmundopop.com/index.php/ioio.html", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/mdg.png"), "https://lojamundodosgames.com/index.php/ioio-capcom.html", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/mercadolivre.png"), "https://lista.mercadolivre.com.br/ioio-capcom#D[A:ioio%20capcom]", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/shoptime.png"), "https://www.shoptime.com.br/busca/ioio-capcom", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/submarino.png"), "https://www.submarino.com.br/busca/ioio-capcom", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/walmart.png"), "https://www.walmart.com.br/busca/?ft=ioio+capcom&PS=40", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/extra.png"), "https://buscando2.extra.com.br/busca?q=ioio+capcom", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/casasbahia.png"), "https://buscas2.casasbahia.com.br/busca?q=ioio+capcom", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/amazon.png"), "https://www.amazon.com.br/s/ref=nb_sb_noss?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=ioio+capcom&rh=i%3Aaps%2Ck%3Aioio+capcom", target:"_blank"  %></div>
         <div class="small-8 large-4 columns"><%= link_to image_tag("icons/agua.png"), "https://www.aguadecheiroonline.com.br/loja/busca.php?loja=575286&palavra_busca=ioio+capcom", target:"_blank"  %></div>

       </div>
     </div>


</section>