config/routes.rb
Rails.application.routes.draw do
  get 'user/show'

  get 'collection/show'

  post 'photo/uploader'

  resources :items

  resources :items do
    resources :photos, :only => [:create, :destroy]
  end

  get 'welcome/index'
  root 'welcome#index'

  get 'sobre', to: 'welcome#about'
  get 'contato', to: 'welcome#contact'
  get 'como-funciona', to: 'welcome#howtodo'
  get 'onde-comprar', to: 'welcome#wherebuy'
  post 'contato', to: 'welcome#email_sender'
  post 'promocao', to: 'welcome#promocao'
  post 'trade', to: 'welcome#trade_sender'
  get 'item-trade', to: 'items#trade'
  get 'promo', to: 'welcome#promo'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_scope :user do
  #  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :photo, :dependent => :destroy
  belongs_to :collection
  belongs_to :user
  belongs_to :status

  scope :actives, -> { where('status_id = ?', 1) }

  def active
    self.status.name == "enable"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :trade]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :index, :new]
  # GET /items
  # GET /items.json
  def index
    #get all itens to current user
    @items = current_user.items
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    if current_user.id != @item.user_id
      redirect_to "/"
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.status_id = 2 #status disable

    respond_to do |format|
      if params[:item][:photo_ids].blank?
        flash[:alert] = 'Por favor selecione as FOTOS.'
        format.html { render :new }
      elsif @item.save

        Photo.where(id: params[:item][:photo_ids]).update_all(item_id: @item.id)
        format.html { redirect_to @item, notice: 'IOIO criado com sucesso.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update

    respond_to do |format|
      if @item.update(item_params)
        Photo.where(id: params[:item][:photo_ids]).update_all(item_id: @item.id)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def trade

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:collection_id, :user_id, :descriprion, :status_id, :code, :photo_ids, :link)
    end
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field select">
    <%= f.label :collection_id, "Modelo do Ioio" %>
    <%= f.select :collection_id, Collection.all.collect { |c| [ c.name, c.id, {'data-image': c.image.thumb} ] }, include_blank: false %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <br>

  <div class="field">
    <%= f.label :code, "N° de Serie do IOIO" %>
    <%= f.text_field :code, min:"1", max:"5000", maxlength:"4", required:"" %>
  </div>

  <div class="field">
    <%= f.label :link, "Video do IOIO" %>
    <%= f.text_field :link, required:"" %>
  </div>

  <div class="field">
    <%= f.label :descriprion, "Algo mais?" %>
    <%= f.text_area :descriprion %>
  </div>

  <div class="field">
    <%= f.label :image, "Limite 5 fotos! A Primeira foto tem que ser do ioio junto com o N° de serie" %>
    <div id="uploaded_photos"></div>
  </div>


  <div class="actions">
    <%= f.file_field :image, multiple: true %>
    <%= f.submit "Cadastrar", class:"item-button mt25" %>

  </div>
<% end %>

app/views/items/edit.html.erb
<%= render "share/slide" %>

<section id="main-content">
  <div class="row">
    <h1>Alteração</h1>
    <h4>
      <div id="user-widget">
        <% if current_user %>
          <%= image_tag current_user.image.thumb %> <strong> <%= current_user.name %></strong>!
        <% else %>
          <%= link_to "<i class=\"fa fa-1x fa-facebook-square\" aria-hidden=\"true\"></i> Entrar com Facebook".html_safe, user_facebook_omniauth_authorize_path, class:"facebook-button" %>
        <% end %>
      </div>
    </h4>


    <%= render 'form', item: @item %>

    <%= link_to 'Ver', @item %> |
    <%= link_to 'Voltar', items_path %>

  </div>
</section>

app/views/items/index.html.erb
<%= render "share/slide" %>

<section id="main-content">

      <div class="row">
        <div class="small-16 columns">
          <h1>Suas aquisições</h1>
          <div class="big-sep"></div>
        </div>
      </div>

      <div class="row">
        <p id="notice"><%= notice %></p>

        <h4>
            <div id="user-widget">
              <% if current_user %>
                <%= image_tag current_user.image.thumb %> <strong> <%= current_user.name %></strong>!
                <%= link_to "Sair", destroy_user_session_path, method: :delete %>
              <% else %>
                <%= link_to "<i class=\"fa fa-1x fa-facebook-square\" aria-hidden=\"true\"></i> Entrar com Facebook".html_safe, user_facebook_omniauth_authorize_path, class:"facebook-button" %>
              <% end %>
            </div>
        </h4>


        <div class="row table">
          <table>
            <thead>
              <tr>
                <th>Coleção</th>
                <th>Foto</th>
                <th>Descrição</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td><%= item.collection.name %></td>
                  <td><%=image_tag item.photo[0].image.thumb %></td>
                  <td><%= item.descriprion %></td>
                  <td><%= link_to 'Ver', item %></td>
                  <td><%= link_to 'Editar', edit_item_path(item) %></td>
                  <td><%= link_to 'Remover', item, method: :delete, data: { confirm: 'Quer mesmo remover?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <br>
        <%=link_to "Cadastre seu IOIO <span>Seja o maior de todos</span>".html_safe, new_item_path, class:"button cta-button" %>
      </div>
</section>

app/views/items/new.html.erb
<%= render "share/slide" %>

<section id="main-content">
  <div class="row">
    <h1>Nova Aquisição  de:</h1>
    <h4>
      <div id="user-widget">
        <% if current_user %>
          <%= image_tag current_user.image.thumb %> <strong> <%= current_user.name %></strong>!
        <% else %>
          <%= link_to "<i class=\"fa fa-1x fa-facebook-square\" aria-hidden=\"true\"></i> Entrar com Facebook".html_safe, user_facebook_omniauth_authorize_path, class:"facebook-button" %>
        <% end %>
      </div>
    </h4>


    <%= render 'form', item: @item %>

  </div>
</section>

app/views/items/show.html.erb
<%= render "share/slide" %>

<section id="main-content">

      <div class="row">
        <div class="small-16 columns">
          <h1>Detalhes</h1>
        </div>
      </div>

      <div class="row game-presentation">
        <div class="small-16 large-9 columns" style="text-align: center;">
          <div class="video-container"><iframe width="100%" height="300" src="https://www.youtube.com/embed/<%= @item.link %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>
          <%#=image_tag @item.photo[0].image.medium, class:"thumbnail" %>
          <div class="thumbnails gallery">
            <% @item.photo.each do |photo| %>
              <%=link_to image_tag(photo.image.thumb), photo.image.url, rel:"prettyPhoto[gallery]", class:"game-gallery thumbnail" %>
            <% end %>
          </div>
        </div>
        <div class="small-16 large-7 columns">
          <div class="game-description">
            <h2><%=link_to image_tag(@item.collection.image.thumb), collection_show_path(id: @item.collection.id) %> <%=link_to @item.collection.name, collection_show_path(id: @item.collection.id) %> #<%= sprintf '%04d', @item.code%></h2>
            <h5>dono: <span class="username"><%= @item.user.name %></span></h5>
            <p>
              <%= @item.descriprion %>
            </p>
          </div>
          <div class="platforms">
            <h5 class="white">Disponível para negociações</h5>

          </div>
          <div class="details-link">
            <%= link_to "Clique aqui", item_trade_path(id: @item.id) %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="small-16 columns">
          <div class="big-sep"></div>
        </div>
      </div>


</section>

<script>
$(function(){
  // Bind the swipeleftHandler callback function to the swipe event on div.box
  $( "div.pp_hoverContainer" ).on( "swipeleft", swipeleftHandler );

  // Callback function references the event target and adds the 'swipeleft' class to it
  function swipeleftHandler( event ){
    alert("left");
    //$( event.target ).addClass( "swipeleft" );
  }
});
</script>

app/views/items/trade.html.erb
<%= render "share/slide" %>

<section id="main-content">

  <div class="row">
    <div class="small-16 columns">
      <h1><span class="white">Negociar com</span> <%= @item.user.name %></h1>
      <div class="big-sep"></div>
    </div>
  </div>

  <div class="row">
    <div class="small-16 large-8 columns">
      <form id="" action="/trade" method="post">
        <label>
          <input type="text" placeholder="Nome" name="name" value="<%= current_user.name if current_user.present? %>">
        </label>

        <label>
          <input type="text" placeholder="Email" name="email">
        </label>

          <input type="text" style="display:none" name="item_id" value="<%= @item.id %>">

        <label>
          <textarea name="message" rows="8" cols="40" placeholder="O que me conta?"></textarea>
        </label>

        <button type="submit" class="lime-button" name="submit">Enviar</button>
      </form>
      <div id="note"></div>
    </div>
    <div class="small-16 large-7 columns addresses">
      <div class="row small-up-1 medium-up-2">
        <!--outros items-->
        <% @item.user.items.each do |item| %>
        <div class="column">
          <h5><%=link_to item.collection.name, collection_show_path(id: item.collection.id) %></h5>
          <address>
            <p>
              CODE: <%= item.code %><br>
              <%=link_to image_tag(item.collection.image.thumb), collection_show_path(id: item.collection.id) %>
            </p>
          </address>
        </div>
        <% end %>
        <!--//end outros-->

      </div>
    </div>
  </div>

</section>